{% set name = "csdms-topoflow-satzone-darcy-layers-balance" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Saturated_Zone-Darcy_Layers
  license: Apache
  summary: |
    SatZoneDarcyLayers is a saturated zone process component included
    within the spatially distributed hydrologic model TopoFlow. It uses
    Darcy's Law, with multiple soil layers, for modeling subsurface flow
    in a saturated zone.
